# Generated by Django 4.0.4 on 2022-06-03 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ansmake_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.TextField(default='faa1772e-a0ba-4655-a734-67f3435f36b4', primary_key=True, serialize=False),
        ),
    ]
